/*
 * eChallan System
 * ### API Specs For eChallan System ### 1. Generate the new challan. 2. Update the details of existing challan 3. Search the existing challan 4. Generate the demand and bill for the challan amount so that collection can be done in online and offline mode. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@egovernments.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.egov.echallancalculation.model;

import java.math.BigDecimal;
import java.util.List;
import java.util.Objects;

import org.egov.common.contract.response.ResponseInfo;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Capture the challan amount details
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-10T16:46:24.044+05:30[Asia/Calcutta]")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Amount {

  @JsonProperty("taxHeadCode")

  private String taxHeadCode = null;

  @JsonProperty("amount")

  private BigDecimal amount = null;
  public Amount taxHeadCode(String taxHeadCode) {
    this.taxHeadCode = taxHeadCode;
    return this;
  }

  

  /**
  * Tax head code from tax head master(Tax codes are desfined at business service level so each business service can have diffrent tax head code defined)
  * @return taxHeadCode
  **/
  public String getTaxHeadCode() {
    return taxHeadCode;
  }
  public void setTaxHeadCode(String taxHeadCode) {
    this.taxHeadCode = taxHeadCode;
  }
  public Amount amount(BigDecimal amount) {
    this.amount = amount;
    return this;
  }

  

  /**
  * Capture the amount for a tax head
  * @return amount
  **/
  public BigDecimal getAmount() {
    return amount;
  }
  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Amount amount = (Amount) o;
    return Objects.equals(this.taxHeadCode, amount.taxHeadCode) &&
        Objects.equals(this.amount, amount.amount);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(taxHeadCode, amount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Amount {\n");
    
    sb.append("    taxHeadCode: ").append(toIndentedString(taxHeadCode)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
