/*
 * eChallan System
 * ### API Specs For eChallan System ### 1. Generate the new challan. 2. Update the details of existing challan 3. Search the existing challan 4. Generate the demand and bill for the challan amount so that collection can be done in online and offline mode. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: contact@egovernments.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.egov.echallan.model;

import java.util.Objects;

import org.egov.echallan.web.models.user.User;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.util.ArrayList;
import java.util.List;

/**
 * This is acting ID token of the authenticated user on the server. Any value provided by the clients will be ignored and actual user based on authtoken will be used on the server.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-08-10T16:46:24.044+05:30[Asia/Calcutta]")
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class UserInfo extends User {

  @JsonProperty("tenantId")

  private String tenantId = null;

  @JsonProperty("uuid")

  private String uuid = null;

  @JsonProperty("userName")

  private String userName = null;

  @JsonProperty("password")

  private String password = null;

  @JsonProperty("idToken")

  private String idToken = null;

  @JsonProperty("mobileNumber")

  private String mobileNumber = null;

  @JsonProperty("email")

  private String email = null;

  @JsonProperty("primaryrole")

  private List<Role> primaryrole = new ArrayList<Role>();

  @JsonProperty("additionalroles")

  private List<TenantRole> additionalroles = null;
  public UserInfo tenantId(String tenantId) {
    this.tenantId = tenantId;
    return this;
  }

}
