swagger: '2.0'
info:
  version: 1.0.0
  title: eGov User Event System.
  description: |
    APIs for Events information. This module handles Below functionality. 
    1. Create/Update new event
    2. Search existing event
    3. An event in the system includes -
       a. System generated events like changes in state of a complaint, PT or TL etc.
       b. Public Message broadcast
       c. Events that happen within an ULB and are published on mSeva.
       d. any other events that are to be notified to the user.
  contact:
    name: eGovernments Foundation
    email: contacts@egovernments.org
schemes:
  - https
basePath: /user-event
x-api-id: org.egov.user.event
x-common-path: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml'
paths:
  /v1/events/_search:
    post:
      summary: Get the list of events defined in the system.
      description: |-
        1. Search and get events based on defined search criteria.
      parameters:
        - $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/parameters/requestInfo'
        - name: status
          in: query
          description: Search based on status.
          type: string
          allowEmptyValue: true
        - name: ids
          type: array
          items:
            type: string
          in: query
          maxItems: 50
          description: unique identifier (uuid) of events
        - name: roles
          type: array
          items:
            type: string
          in: query
          maxItems: 50
          description: Array of roles for which the events are being searched.
        - name: userIds
          type: array
          items:
            type: string
          in: query
          maxItems: 50
          description: unique identifier (uuid) of of th users.
        - name: postedBy
          type: array
          items:
            type: string
          in: query
          maxItems: 50
          description: unique identifier (uuid) of the employees posting the event.
        - name: date
          type: integer
          in: query
          maxItems: 50
          description: epoch date of posting the event.
        - name: tenantId
          in: query
          description: unique identifier of the ULB.
          type: string
          allowEmptyValue: false
      responses:
        '200':
          description: Events Retrived Successfully
          schema:
            $ref: '#/definitions/EventResponse'
        '400':
          description: Invalid input.
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/ErrorRes'
      tags:
        - Events
        
  /v1/events/_create:
    post:
      summary: Create new Event
      description: |
      parameters:
        - name: EventRequest
          in: body
          description: Details for the new Events + RequestInfo meta data.
          required: true
          schema:
            $ref: '#/definitions/EventRequest'
      responses:
        '201':
          description: ReponseInfo with Events created successfully
          schema:
            $ref: '#/definitions/EventResponse'
        '400':
          description: Events creation failed
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'
      tags:
        - Events
        
  /v1/events/_update:
    post:
      summary: Update existing events
      description: |-
        This API is used to update existing events in the system.
      parameters:
        - name: EventRequest
          in: body
          description: Details for the new Events + RequestInfo meta data.
          required: true
          schema:
            $ref: '#/definitions/EventRequest'
      responses:
        '201':
          description: ReponseInfo with Events updated sudcessfully
          schema:
            $ref: '#/definitions/EventResponse'
        '400':
          description: Events(s) updation failed
          schema:
            $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ErrorRes'
      tags:
        - Events
        
        
        
        
definitions:
  Action:
    type: object
    description: Object holds that holds basic data for actions associated to an event. 
    properties:
      tenantId:
        type: string
        description: Unique Identifier of ULB
        maxLength: 128
        minLength: 2
      id:
        type: string
        minLength: 2
        maxLength: 64
        description: Unique Identifier of the action (UUID)
      eventId:
        type: string
        description: Event Id for which this action is applicable.
        maxLength: 64
        minLength: 2
      actionUrls:
        description: Array of action urls and labels.
        type: array
        minimum: 1
        maximum: 100
        items:
          $ref: '#/definitions/ActionItem'
      auditDetails:
        $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/AuditDetails'
    required:
      - tenantId
      
  
  Event:
    type: object
    description: A Object holds the basic data for an Event.
    properties:
      tenantId:
        type: string
        description: Unique Identifier of ULB
        maxLength: 128
        minLength: 2
      id:
        type: string
        minLength: 2
        maxLength: 64
        description: Unique Identifier of the Event (UUID)
      eventType:
        type: string
        description: This MDMS master data to diffrenciate the category of event which is namespaced. 
        maxLength: 32
        minLength: 2
      description:
        type: string
        description: Description of the event 
        maxLength: 1024
        minLength: 2
      status:
        type: string
        description: Status of the event in the system. Can hold one of the following enum values.
        enum:
          - Active
          - Inactive
          - Canceled
      toRoles:
          type: array
          items:
            type: string
          description: Array of roles of the receipients of this notification.
      toUsers:
          type: array
          items:
            type: string
          description: Array of ids (uuids) of the receipients of this notification.
      actions:
        type: object
        description: Action to be taken on this event. For instance, whenever a complaint is resolved, the 
            user can take 2 actions namely - REOPEN and RATE. 
        $ref: '#/definitions/Action'
      eventDetails:
        type: object
        description: Details of the event like time, venue and some other optional details.
        $ref: '#/definitions/EventDetails'
      auditDetails:
        $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/AuditDetails'
    required:
      - tenantId
      
      
  ActionItem:
    type: object
    description: Object that holds basic data for actionable url associated to an action. 
    properties:
      actionUrl:
        type: string
        description: This is redirection url.
        maxLength: 128
        minLength: 2
      code:
        type: string
        description: Code is to fetch localisation name for each action. This is applicable only if there are more then one actions are available for single event. 
        maxLength: 32
        minLength: 2
    required:
      - tenantId
      
      
  EventDetails:
    type: object
    description: Object that holds details such as time, venue etc of an event. 
    properties:
      fromDate:
        type: string
        description: Start date of event.
        maxLength: 32
        minLength: 2
      toDate:
        type: string
        description: End date of event.
        maxLength: 32
        minLength: 2
      latitude:
        type: number
        description: latitude value of the location.
      longitude:
        type: number
        description: longitude value of the location.
      documents:
        type: array
        description: List of file store ids.
        maximum: 5
        items:
          type: string
    required:
      - tenantId
      
  
  EventRequest:
    description: 'Contract class to receive request. Array of Event items are used in case of create and update'
    properties:
      RequestInfo:
        $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-1-1.yml#/definitions/RequestInfo'
      Events:
        description: Array of events to be created in the system.
        type: array
        minimum: 1
        maximum: 100
        items:
          $ref: '#/definitions/Event'
          
  EventResponse:
    description: 'Contract class to send response. Array of Event items are used in case of search results or response for create and update'
    properties:
      ResponseInfo:
        $ref: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/common/contracts/v1-0-0.yml#/definitions/ResponseInfo'
      Events:
        description: Array of events to be received from the system.
        type: array
        maximum: 500
        items:
          $ref: '#/definitions/Event'

tags:
  - name: Events
    description: APIs required for Event handling.
